"""
park_data.py

Hardcoded databases with:
1) Park Biome Tags
2) Park language profiles (terms + noun chunks)
3) Biome language profiles (terms + noun chunks)

Notes:
- Items lowercase.
- Terms should be single words (no spaces).
- Chunks should be multi-word phrases (contain spaces).
"""

from __future__ import annotations

from typing import Dict, List, Set, Tuple

# -----------------------------
# California National Parks
# -----------------------------
PARKS: Tuple[str, ...] = (
    "Channel Islands",
    "Death Valley",
    "Joshua Tree",
    "Kings Canyon",
    "Lassen Volcanic",
    "Pinnacles",
    "Redwood",
    "Sequoia",
    "Yosemite",
)

# -----------------------------
# Biome Tags
# -----------------------------
BIOMES: Tuple[str, ...] = (
    "Marine_Costal",
    "Dessert",
    "Forrest",
    "Mountains_Hills",
    "Rivers_Lakes",
    "Meadows_Flowers",
    "Volcanic_Fire",
)

# --------------------------------------
# Park Biomes
# --------------------------------------
PARK_BIOMES: Dict[str, List[str]] = {
    "Channel Islands": ["Marine_Costal"],
    "Death Valley": ["Dessert"],
    "Joshua Tree": ["Dessert"],
    "Pinnacles": ["Dessert", "Meadows_Flowers"],
    "Redwood": ["Forrest"],
    "Sequoia": ["Forrest"],
    "Yosemite": ["Mountains_Hills", "Rivers_Lakes", "Meadows_Flowers"],
    "Kings Canyon": ["Mountains_Hills", "Rivers_Lakes"],
    "Lassen Volcanic": ["Mountains_Hills", "Volcanic_Fire"],
}

# ============================================================
# 1) PARK LANGUAGE DATABASE
# ============================================================

PARK_TERMS: Dict[str, List[str]] = {
    "Channel Islands": [
        "island",
        "channel",
        "coast",
        "ocean",
        "sea",
        "kelp",
        "tide",
        "surf",
        "shore",
        "harbor",
        "seal",
        "sea lion",
        "whale",
        "dolphin",
        "gull",
        "pelican",
        "brine",
        "spray",
        "cliff",
        "bluff",
        "cove",
        "anchorage",
        "marine",
        "fog",
        "wind",
        "sandstone",
    ],
    "Death Valley": [
        "desert",
        "dune",
        "sand",
        "salt",
        "basin",
        "badlands",
        "canyon",
        "butte",
        "mesa",
        "mirage",
        "heat",
        "sun",
        "arid",
        "dry",
        "cracked",
        "alkali",
        "scorch",
        "barren",
        "gully",
        "ravine",
        "windswept",
        "sage",
        "creosote",
        "pan",
    ],
    "Joshua Tree": [
        "desert",
        "cactus",
        "yucca",
        "joshua",
        "boulder",
        "granite",
        "sand",
        "basin",
        "sky",
        "star",
        "moon",
        "arid",
        "dry",
        "spine",
        "thorn",
        "ocotillo",
        "cholla",
        "scrub",
        "ridge",
        "hike",
        "climb",
        "sunrise",
        "twilight",
    ],
    "Kings Canyon": [
        "canyon",
        "river",
        "creek",
        "waterfall",
        "granite",
        "pine",
        "fir",
        "cedar",
        "forest",
        "ridge",
        "peak",
        "alpine",
        "snow",
        "meadow",
        "valley",
        "trail",
        "glacier",
        "lake",
        "basin",
        "gorge",
        "cascade",
        "roar",
    ],
    "Lassen Volcanic": [
        "volcano",
        "lava",
        "basalt",
        "cinder",
        "crater",
        "caldera",
        "steam",
        "fumarole",
        "sulfur",
        "geyser",
        "thermal",
        "ash",
        "pumice",
        "obsidian",
        "fire",
        "burn",
        "mountain",
        "snow",
        "lake",
        "pine",
        "ridge",
        "eruption",
    ],
    "Pinnacles": [
        "pinnacle",
        "spire",
        "talus",
        "cave",
        "chaparral",
        "oak",
        "grass",
        "wildflower",
        "meadow",
        "ridge",
        "canyon",
        "rock",
        "crag",
        "condor",
        "hawk",
        "sun",
        "heat",
        "dry",
        "scrub",
        "trail",
        "hike",
        "bloom",
    ],
    "Redwood": [
        "redwood",
        "coast",
        "fog",
        "fern",
        "moss",
        "grove",
        "canopy",
        "forest",
        "creek",
        "river",
        "salmon",
        "trail",
        "damp",
        "shade",
        "cathedral",
        "ancient",
        "tower",
        "giant",
        "mist",
        "coastal",
        "spruce",
    ],
    "Sequoia": [
        "sequoia",
        "giant",
        "grove",
        "tree",
        "trunk",
        "bark",
        "forest",
        "granite",
        "dome",
        "canyon",
        "alpine",
        "snow",
        "meadow",
        "ridge",
        "peak",
        "trail",
        "high",
        "thin",
        "pine",
        "bear",
    ],
    "Yosemite": [
        "yosemite",
        "granite",
        "dome",
        "cliff",
        "wall",
        "valley",
        "river",
        "creek",
        "waterfall",
        "cascade",
        "pine",
        "fir",
        "meadow",
        "wildflower",
        "alpine",
        "snow",
        "peak",
        "ridge",
        "glacier",
        "trail",
        "mist",
        "thunder",
    ],
}

PARK_CHUNKS: Dict[str, List[str]] = {
    "Channel Islands": [
        "kelp forest",
        "rocky shore",
        "sea cave",
        "tide pool",
        "marine terrace",
        "coastal bluff",
        "salt spray",
        "ocean swell",
        "harbor seal",
        "sea lion rookery",
    ],
    "Death Valley": [
        "salt flats",
        "sand dunes",
        "dry lakebed",
        "desert basin",
        "badlands ridge",
        "scorched earth",
        "cracked clay",
        "wind carved canyon",
        "sun baked rock",
    ],
    "Joshua Tree": [
        "joshua tree",
        "granite boulders",
        "desert night sky",
        "cactus garden",
        "rocky wash",
        "high desert",
        "hidden valley",
        "boulder field",
    ],
    "Kings Canyon": [
        "deep canyon",
        "granite gorge",
        "alpine lake",
        "river canyon",
        "pine forest",
        "high country",
        "glacial valley",
        "roaring waterfall",
        "wide meadow",
    ],
    "Lassen Volcanic": [
        "cinder cone",
        "lava field",
        "sulfur vents",
        "boiling springs",
        "steam plume",
        "volcanic crater",
        "obsidian flow",
        "thermal basin",
        "ash covered slope",
    ],
    "Pinnacles": [
        "rock spires",
        "talus cave",
        "chaparral hills",
        "spring wildflowers",
        "rolling grassland",
        "condor flight",
        "sunlit ridges",
    ],
    "Redwood": [
        "redwood grove",
        "coastal fog",
        "fern lined trail",
        "mossy forest",
        "cathedral canopy",
        "ancient giants",
        "misty creek",
    ],
    "Sequoia": [
        "giant sequoias",
        "sequoia grove",
        "granite domes",
        "high sierra",
        "alpine meadow",
        "snowy peaks",
        "deep canyon",
    ],
    "Yosemite": [
        "granite walls",
        "glacial valley",
        "towering waterfall",
        "misty cascade",
        "wildflower meadow",
        "river bend",
        "pine scented air",
        "granite dome",
    ],
}

# ============================================================
# 2) BIOME LANGUAGE DATABASE
# ============================================================

BIOME_TERMS: Dict[str, List[str]] = {
    "Marine_Costal": [
        "ocean",
        "sea",
        "marine",
        "coast",
        "coastal",
        "island",
        "kelp",
        "tide",
        "surf",
        "shore",
        "spray",
        "brine",
        "harbor",
        "seal",
        "gull",
        "whale",
        "fog",
        "salt",
        "cove",
    ],
    "Dessert": [
        "desert",
        "arid",
        "dry",
        "dune",
        "sand",
        "cactus",
        "yucca",
        "heat",
        "sun",
        "mirage",
        "barren",
        "scrub",
        "mesa",
        "butte",
        "salt",
        "basin",
    ],
    "Forrest": [
        "forest",
        "grove",
        "canopy",
        "tree",
        "redwood",
        "sequoia",
        "fern",
        "moss",
        "shade",
        "damp",
        "mist",
        "loam",
        "understory",
        "trail",
    ],
    "Mountains_Hills": [
        "mountain",
        "hill",
        "ridge",
        "peak",
        "summit",
        "alpine",
        "granite",
        "cliff",
        "crag",
        "snow",
        "glacier",
        "basin",
        "high",
    ],
    "Rivers_Lakes": [
        "river",
        "creek",
        "stream",
        "waterfall",
        "cascade",
        "rapids",
        "lake",
        "shoreline",
        "pool",
        "confluence",
        "ford",
        "wet",
        "current",
    ],
    "Meadows_Flowers": [
        "meadow",
        "wildflower",
        "bloom",
        "petal",
        "grass",
        "prairie",
        "spring",
        "field",
        "blossom",
        "pollen",
        "nectar",
        "butterfly",
    ],
    "Volcanic_Fire": [
        "volcano",
        "lava",
        "basalt",
        "cinder",
        "crater",
        "caldera",
        "obsidian",
        "ash",
        "pumice",
        "fumarole",
        "sulfur",
        "steam",
        "thermal",
        "fire",
        "ember",
    ],
}

BIOME_CHUNKS: Dict[str, List[str]] = {
    "Marine_Costal": [
        "kelp forest",
        "tide pool",
        "rocky shore",
        "coastal bluff",
        "salt spray",
        "ocean swell",
        "sea cave",
    ],
    "Dessert": [
        "sand dunes",
        "salt flats",
        "dry lakebed",
        "high desert",
        "sun baked rock",
        "arid basin",
    ],
    "Forrest": [
        "old growth forest",
        "redwood grove",
        "mossy trail",
        "fern covered floor",
        "cathedral canopy",
    ],
    "Mountains_Hills": [
        "granite ridge",
        "alpine peak",
        "snowy summit",
        "glacial valley",
        "rocky cliffs",
    ],
    "Rivers_Lakes": [
        "roaring waterfall",
        "river bend",
        "mountain creek",
        "glacial lake",
        "rushing rapids",
    ],
    "Meadows_Flowers": [
        "wildflower meadow",
        "spring bloom",
        "grassy field",
        "flowered hills",
    ],
    "Volcanic_Fire": [
        "lava field",
        "cinder cone",
        "sulfur vents",
        "steam plume",
        "volcanic crater",
        "thermal basin",
    ],
}